services:
  bot:
    build: .
    volumes:
      - ./src:/app/src
      - ./users.db:/app/users.db
    restart: unless-stopped
    network_mode: host
    logging:
      driver: local
      options:
        max-size: "20m"
        max-file: "5"
